using System.Text.Json;
using Domain.Interfaces;
using Domain.Models;
using Logistic.Application.Mappers;

namespace Logistic.Application.Services;

public class AutogeneratedBusinessService<T> where T : BaseModel 
{
    public List<string> ActionErrors { get; }
    
    private readonly IBaseModelsRepository<T> _repository;
    private readonly AutogeneratedMapper<T> _mapper;

    public AutogeneratedBusinessService(IBaseModelsRepository<T> repository)
    {
        _repository = repository;
        _mapper = new AutogeneratedMapper<T>();
        ActionErrors = new List<string>();
    }
    
    public virtual List<object> GetList()
    {
        var entities = _repository.GetList().ToList();

        return entities.Select(entity => _mapper.MapFromDomain(entity)).ToList();
    }
    
    public virtual object? Get(long id)
    {
        var entity = _repository.Get(id);

        if (entity == null)
            throw new Exception("Для указанного id не найдена сущность");

        return _mapper.MapFromDomain(entity);
    }

    public async virtual Task Update(List<object> entities)
    {
        var domainEntities = new List<T>();
        foreach (var entity in entities)
        {
            var domainEntitiy = _mapper.MapToDomain((JsonElement)entity);
            
            if (domainEntitiy != null)
                domainEntities.Add(domainEntitiy);
        }
    }
}