using Domain.Models;
using Logistic.Application.BusinessModels;
using Logistic.Application.Services;
using Logistic.Dto.Requests;
using Logistic.Dto.Responses;
using Logistic.Enums;
using Microsoft.AspNetCore.Mvc;

namespace Logistic.Controllers;

[ApiController]
[Route("[controller]/[action]")]
public class AutogeneratedController<T> : Controller where T : BaseModel
{
    private readonly AutogeneratedBusinessService<T> _service;

    public AutogeneratedController(AutogeneratedBusinessService<T> service)
    {
        _service = service;
    }

    [HttpGet(nameof(List))]
    public LogisticWebResponse List()
    {
        var result = new LogisticWebResponse();
        result.Data = _service.GetList();
        result.Flags.Add(Flag.Autogenerated.ToString());
        
        return result;
    }
    
    [HttpGet(nameof(Get))]
    public LogisticWebResponse Get(long id)
    {
        var result = new LogisticWebResponse();
        var entity = _service.Get(id);
        if (entity != null)
            result.Data.Add(entity);
        
        result.Flags.Add(Flag.Autogenerated.ToString());
        
        return result;
    }
    
    [HttpPost(nameof(Change))]
    public async Task<ObjectResult> Change(LogisticWebRequestForAutogeneration form)
    {
        var entities = form.Data;
        await _service.Update(entities);

        if (!_service.ActionErrors.Any())
            return new LogisticWebResponse()
            {
                Notification = "Изменение успешно"
            }.AsObjectResult();

        return LogisticWebResponse.BadResult(_service.ActionErrors).AsObjectResult();
    }
}