using Domain.Models;
using Logistic.Application;
using Logistic.Dto.Responses;
using Logistic.Enums;
using Microsoft.AspNetCore.Mvc;

namespace Logistic.Controllers;

public class BaseController<T> : Controller where T : BaseModel
{
    private readonly IBaseBusinessService<T> _service;

    public BaseController(IBaseBusinessService<T> service)
    {
        _service = service;
    }

    [HttpGet(nameof(List))]
    public LogisticWebResponse List()
    {
        var result = new LogisticWebResponse();
        result.Data = _service.GetList().Cast<object>().ToList();
        result.Flags.Add(Flag.Autogenerated.ToString());
        
        return result;
    }
    
    [HttpGet(nameof(Get))]
    public LogisticWebResponse Get(long id)
    {
        var result = new LogisticWebResponse();
        var entity = _service.Get(id);
        if (entity != null)
            result.Data.Add(entity);
        
        result.Flags.Add(Flag.Autogenerated.ToString());
        
        return result;
    }
}