using Domain.Models;
using Logistic.Application;
using Logistic.Dto.Responses;
using Microsoft.AspNetCore.Mvc;

namespace Logistic.Controllers;

public class BaseController<T> : Controller where T : BaseModel
{
    private IBaseBusinessService<T> _service;

    public BaseController(IBaseBusinessService<T> service)
    {
        _service = service;
    }

    [HttpGet(nameof(List))]
    public BaseListForm<T> List()
    {
        var result = new BaseListForm<T>();
        result.Entities = _service.GetList().ToList();
        result.IsAutogenerated = true;
        
        return result;
    }
    
    [HttpGet(nameof(Get))]
    public BaseGetForm<T> Get(long id)
    {
        var result = new BaseGetForm<T>();
        result.Entity = _service.Get(id);
        result.IsAutogenerated = true;
        
        return result;
    }
}