using Domain.WorkResults;
using Logistic.Application;
using Logistic.Enums;
using Logistic.Infrastructure.WorkResult;
using Logistic.Interfaces;
using Logistic.WorkResult;
using Microsoft.AspNetCore.Mvc;

namespace Logistic.Dto.Responses;

public class LogisticWebResponse : ActionResult
{
    public List<object> Data { get; set; }
    public List<ActionMessage> Messages { get; set; } = new List<ActionMessage>();
    public List<string> Flags { get; } = new List<string>();
    private readonly int _statusCode;

    public LogisticWebResponse()
    {
        Data = new List<object>();
        _statusCode = 200;
    }
    
    public LogisticWebResponse(List<object> data)
    {
        Data = data;
        _statusCode = 200;
    }
    
    public LogisticWebResponse(List<object> data, IPresentationActionMessageContainer results)
    {
        Data = data;
        Messages = results.Messages;
        _statusCode = results.GetStatusCode();
    }

    public ObjectResult AsObjectResult()
    {
        return new ObjectResult(this)
        {
            StatusCode = _statusCode
        };
    }

    public void MarkAutogenerated()
    {
        Flags.Add(Flag.Autogenerated.ToString());
    }
}