using System.Reflection;
using Domain.Attributes;
using Domain.Interfaces;
using Domain.Models;
using Logistic.Application.BusinessModels;
using Logistic.Application.Mappers;
using Logistic.Application.Services;
using Logistic.Application.Validators;
using Logistic.Infrastructure.Repositories;
using Microsoft.Extensions.DependencyInjection;

namespace Logistic.Application;

public static class Business
{
    public static void AddBusinessGeneration(this IServiceCollection services)
    {
        var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == "Logistic.Domain");
        var autoGeneratableTypes = assembly
            .GetTypes()
            .Where(t => t.GetCustomAttributes(typeof(AutoGenerateAttribute), true).Any());

        foreach (var type in autoGeneratableTypes)
        {
            //var baseBusinessInterfaceType = typeof(IBaseBusinessService<>).MakeGenericType(type);
            var baseBusinessServiceType = typeof(AutogeneratedBusinessService<>).MakeGenericType(type);
            /*var implementationType =
                Assembly.GetExecutingAssembly().GetType($"{type.Namespace}.Services.{type.Name}Service");*/

            services.AddScoped(baseBusinessServiceType, baseBusinessServiceType);
        }

    }
    
    public static void AddBusinessDependencies(this IServiceCollection services)
    {
        services.AddScoped<CustomerService, CustomerService>();
        AddMappers(services);
        AddValidators(services);
    }

    private static void AddMappers(IServiceCollection services)
    {
        services.AddScoped<IDomainMappable<Customer,CustomerBusiness>, CustomerBusinessMapper>();
    }

    private static void AddValidators(IServiceCollection services)
    {
        services.AddScoped<IValidatable<CustomerBusiness>, CustomerBusinessValidator>();
    }
}