using System.Dynamic;
using System.Reflection;
using System.Text.Json;
using Domain.Models;

namespace Logistic.Application.Mappers;

public class AutogeneratedMapper<TDomain> where TDomain : BaseModel
{
    public object MapFromDomain(TDomain entity)
    {
        var type = entity.GetType();
        var result = new ExpandoObject() as IDictionary<string, object?>;
        foreach (var field in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!field.CanRead)
                continue;

            result.Add(field.Name, field.GetValue(entity));
        }
        
        return result;
    }
    
    public TDomain? MapToDomain(JsonElement entity)
    {
        var type = typeof(TDomain);
        var constructor = type.GetConstructor(new Type[] {});
        var result = (TDomain) constructor?.Invoke(new TDomain[] { });
        
        foreach (var field in typeof(TDomain).GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            var isPropertyInRequest = entity.TryGetProperty(field.Name, out JsonElement requestProperty);
            
            if (!isPropertyInRequest)
                continue;

            var value = GetValueForPropertyInJson(field, requestProperty);
            field.SetValue(result, value);
        }
        
        return result;
    }

    private object? GetValueForPropertyInJson(PropertyInfo field, JsonElement value)
    {
        var valueKind = value.ValueKind;
        var propertyTypeName = field.PropertyType.Name;
        var propertyType = field.PropertyType;
        if (field.PropertyType.IsSubclassOf(typeof(BaseModel)))
            propertyTypeName = "BaseModelChild";

        switch (propertyTypeName)
        {
            case "Int64":
                return (valueKind == JsonValueKind.Number) ? value.GetInt64() : null;
            case "String":
                return (valueKind == JsonValueKind.String) ? value.GetString() : null;
            case "BaseModelChild": 
                var JSONCovert = typeof(JsonSerializer);
                var parameterTypes = new[] { typeof(JsonElement), typeof(JsonSerializerOptions) };
                var deserializer = JSONCovert
                    .GetMethods(BindingFlags.Public | BindingFlags.Static)
                    .Where(i => i.Name.Equals("Deserialize", StringComparison.InvariantCulture))
                    .Where(i => i.IsGenericMethod)
                    .Single(i => i.GetParameters().Select(a => a.ParameterType).SequenceEqual(parameterTypes));
                var options = new JsonSerializerOptions();
                var genericMethodInfo = deserializer.MakeGenericMethod(propertyType);
                return (valueKind == JsonValueKind.Object) ?  genericMethodInfo.Invoke(value, new object[] { value, options }) : null;
            case "Boolean": 
                return valueKind is JsonValueKind.True or JsonValueKind.False ? value.GetBoolean() : null;
            default:
                return null;
        }
    }
    
}