using Domain.Interfaces;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Logistic.Infrastructure.Repositories;

//ToDo: расписать на подзадачи и оценить добавление интерсепторов.
public class AutogeneratedRepository<T> : IBaseModelsRepository<T> where T : BaseModel
{
    private DataBaseContext _db;
    private readonly IServiceProvider _serviceProvider;

    public AutogeneratedRepository(DataBaseContext db, IServiceProvider serviceProvider)
    {
        _db = db;
        _serviceProvider = serviceProvider;
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    public IEnumerable<T> GetList()
    {
        var result = _db.Set<T>().ToList();

        if (result.Count > 0)
            IncludeForeignKeys();
        
        return result;
    }

    public T? Get(long id)
    {
        var entity =  _db.Set<T>().Find(id);

        if (entity != null)
        {
            IncludeForeignKeys();
        }
        
        return entity;
    }

    public void Create(T item)
    {
        _db.Set<T>().Add(item);
    }

    public void Update(T item)
    {
        _db.Entry(item).State = EntityState.Modified;
        UpdateForeignKeys(item);
    }

    public void Delete(long id)
    {
        var entity = _db.Set<T>().Find(id);
        if (entity != null)
            _db.Set<T>().Remove(entity);
    }

    public async Task SaveAsync()
    {
        await _db.SaveChangesAsync();
    }
    
    private bool disposed = false;
    public virtual void Dispose(bool disposing)
    {
        if (!disposed)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
        disposed = true;
    }

    private void IncludeForeignKeys()
    {
        var entityType = typeof(T);
        var baseModelType = typeof(BaseModel);

        foreach (var property in entityType.GetProperties())
        {
            if (baseModelType.IsAssignableFrom(property.PropertyType))
                _db.Set<T>().Include(property.Name).Load();
        }
    }
    
    private void UpdateForeignKeys(T currentEntity)
    {
        var entityType = typeof(T);
        var baseModelType = typeof(BaseModel);

        foreach (var property in entityType.GetProperties())
        {
            if (!baseModelType.IsAssignableFrom(property.PropertyType))
                continue;
            
            var type = typeof(IBaseModelsRepository<>).MakeGenericType(property.PropertyType);
            var propertyRepo = _serviceProvider.GetRequiredService(type);
            if (propertyRepo == null)
                continue;
            
            var method = type.GetMethod("Get", new Type[] { typeof(long) });
            if (method == null)
                continue;
            
            var linkValue = property.GetValue(currentEntity); 
            if (linkValue == null)
                continue;

            var id = ((BaseModel) linkValue).id;
            
            var result = method.Invoke(propertyRepo, new object[] { id });
            property.SetValue(currentEntity, result);
        }
    }
}